-- CreateTable
CREATE TABLE "VendorApplication" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "vendor_type" TEXT NOT NULL,
    "company_name" TEXT NOT NULL,
    "business_type" TEXT NOT NULL,
    "tax_id" TEXT,
    "vat_number" TEXT,
    "country_of_incorporation" TEXT,
    "primary_contact_name" TEXT NOT NULL,
    "primary_contact_email" TEXT NOT NULL,
    "primary_contact_phone" TEXT,
    "business_address" TEXT,
    "city" TEXT,
    "state" TEXT,
    "zip_code" TEXT,
    "country" TEXT NOT NULL,
    "website" TEXT,
    "industry" TEXT NOT NULL,
    "years_in_business" INTEGER,
    "annual_revenue_range" TEXT,
    "services_offered" TEXT,
    "business_license_url" TEXT,
    "tax_document_url" TEXT,
    "insurance_certificate_url" TEXT,
    "business_registration_url" TEXT,
    "certificate_of_good_standing_url" TEXT,
    "bank_details_document_url" TEXT,
    "import_export_license_url" TEXT,
    "compliance_certificates_url" TEXT,
    "vat_registration_url" TEXT,
    "bank_name" TEXT,
    "bank_account_number" TEXT,
    "swift_code" TEXT,
    "iban" TEXT,
    "preferred_currency" TEXT,
    "status" TEXT NOT NULL,
    "admin_notes" TEXT,
    "rejection_reason" TEXT,
    "approved_date" TEXT,
    "created_date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);
